[[Init]]
trigger = "Homed"
condition = "!isScoringTestMode()"
destination = "Idle"
[[Init]]
trigger = "Homed"
condition = "isScoringTestMode()"
destination = "TestMode"
[[Init]]
trigger = "ForceInit"
destination = "Idle"

[[Idle]]
trigger = "StartWarmup"
condition = "hasGamePiece()"
destination = "Warmup"
[[Idle]]
trigger = "TestModeEntered"
condition = "isScoringTestMode()"
destination = "TestMode"

[[TestMode]]
trigger = "TestModeExitted"
condition = "!isScoringTestMode()"
destination = "Idle"

[[Warmup]]
trigger = "WarmupCancelled"
destination = "Idle"
[[Warmup]]
trigger = "WarmupReady"
condition = "hasGamePiece() && warmupReady()"
destination = "Score"

[[Score]]
trigger = "DoneScoring"
condition = "!hasGamePiece()"
destination = "Idle"
[[Score]]
trigger = "WarmupCancelled"
destination = "Idle"
